class Lex:
	PRINT 		= '@'
	SEMICOLON 	= ';'
	COMMA 		= ','
	EQUAL 		= '='
	ADD 		= '+'
	SUBTRACT 	= '-'
	MULTIPLY 	= '*'
	DIVIDE 		= '/'
	LPAR 		= '('
	RPAR 		= ')'
	NEWLINE 	= '\n'
	SPACE 		= ' '
	TAB 		= '\t'
	PERIOD		= '.'
