#!/usr/bin/env python
# -*- coding:utf-8 -*-
# 
# UnitX: 
#
#

import parser
import sys
if len(sys.argv) < 2: sys.exit(1)

a_filepath = sys.argv[1]
#with open(a_filepath, 'r') as rf:
#a_code = rf.read()
a_parser = parser.MainParser(a_filepath)
a_parser.parse()

#if __name__ == '__main__':
	
