#!/usr/bin/env python
# -*- coding:utf-8 -*-
# 
# UnitX: 
#
#

import sys
import parser

def main():
	if len(sys.argv) < 2: sys.exit(1)
	a_filepath = sys.argv[1]
	a_parser = parser.MainParser(a_filepath)
	a_parser.parse()

if __name__ == '__main__':
	main()
