#!/usr/bin/env python
# -*- coding:utf-8 -*-
# 
# UnitX: 
#
#


import sys
from antlr4 import *
from antlr4.InputStream import InputStream
from UnitXLexer import UnitXLexer
from UnitXParser import UnitXParser

def main(argv):
	if len(argv) > 1:
		input_stream = FileStream(argv[1], encoding='utf-8')
	else:
		input_stream = InputStream(sys.stdin.readline())

	lexer = UnitXLexer(input_stream)
	token_stream = CommonTokenStream(lexer)
	parser = UnitXParser(token_stream)
	tree = parser.program()

	lisp_tree_str = tree.toStringTree(recog=parser)
	print(lisp_tree_str)

if __name__ == '__main__':
	main(sys.argv)
